<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
        <PackageReference Include="coverlet.msbuild" Version="6.0.4" PrivateAssets="all" />
        <PackageReference Include="coverlet.collector" Version="6.0.4" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ChipEight.Machine\ChipEight.Machine.csproj" />
      <ProjectReference Include="..\ChipEight.Machine\ChipEight.Machine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Roms\2-ibm-logo.ch8">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Roms\1-chip8-logo.ch8">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Roms\3-corax+.ch8">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Roms\4-flags.ch8">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
